#!/usr/bin/perl -w
#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use esmith::Build::CreateLinks qw(:all);


my @templates = qw(
    /etc/freshclam.conf
    /etc/clamav-unofficial-sigs/clamav-unofficial-sigs.conf
    /etc/sysconfig/freshclam
);

#
# nethserver-antivirus-UPDATE event
#

event_templates('nethserver-antivirus-update', @templates);

event_actions('nethserver-antivirus-update',
	      'initialize-default-databases' => '00',
	      'nethserver-antivirus-init-avdb' => '30');

#
# proxy-modify event and action
#

event_templates('proxy-modify', qw(
    /etc/freshclam.conf
));

event_actions('proxy-modify', qw(
    nethserver-antivirus-init-avdb 30
));
