#!/bin/bash

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

function instance_data() {
    instance=$1
    instance_directory=/etc/clamd.d/$instance.conf

    if [ ! -f "$instance_directory" ]; then
        # instance is not installed
        is_installed=false
        is_active=false
        num_malware=0
        num_signatures=0
        chart_entries=""
        memory_used=0
        since=0
    else
        is_installed=true
        status=$(systemctl is-active clamd@$instance)

        if [ "$status" == "active" ]; then
            is_active=true
            memory_used=$(cat /proc/$(pgrep -f /etc/clamd.d/$instance.conf)/status | grep VmSize | awk '{print $2}')
        else
            is_active=false
            memory_used=0
        fi

        num_malware=$(journalctl -u clamd@$instance | grep FOUND | wc -l)
        if [ -z "$num_malware" ]; then
            num_malware=0
        fi

        num_signatures=$(journalctl -u clamd@$instance | sed -nr "s/.*[^0-9]([0-9]+) signatures.*/\1/p" | tail -n 1)
        if [ -z "$num_signatures" ]; then
            num_signatures=0
        fi

        # malware chart data

        chart_data=$(journalctl -u clamd@$instance  | grep FOUND | awk '{print $7}' | sed -r "s/(.*)\.UNOFFICIAL/\1/" | sort | uniq -c)
        chart_entries=""

        IFS=$'\n'
        for line in $chart_data
        do
            chart_entries=$chart_entries[\"`echo $line | awk '{print $2}'`\",`echo $line | awk '{print $1}'`],
        done
        unset IFS

        # remove trailing comma if there is at lest one entry
        if [[ $chart_entries ]]; then
            chart_entries=${chart_entries::-1}
        fi

        # since
        since_iso=$(journalctl -u clamd@$instance -o short-iso | head -n2 | tail -n1 | awk '{print $1}')
        if [ "$since_iso" == "--" ]; then
            # no journal entries
            since=0
        else
            since=$(date -d "$since_iso" +"%s")
        fi
    fi

    echo "\"$instance\": { \"installed\": $is_installed, \"active\": $is_active, \"malwareFound\": $num_malware, \"signatures\": $num_signatures, \"malwareStats\": [$chart_entries], \"memoryUsedKb\": $memory_used, \"since\": $since }"
}

rspamd_data=$(instance_data rspamd)
squidclamav_data=$(instance_data squidclamav)

# signatures last updated
signatures_directory=/var/lib/clamav
if [ -d "$signatures_directory" ]; then
    signatures_updated=$(stat  -c "%Y"  $(find /var/lib/clamav -type f -printf '%T@ %p\n' | sort -n | tail -1 | cut -f2- -d" "))
else
    signatures_updated=0
fi

echo -n "{ $rspamd_data, $squidclamav_data, \"signaturesUpdated\": $signatures_updated }"
