#!/bin/bash

#
# Copyright (C) 2019 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

. /usr/libexec/nethserver/api/lib/helper_functions

# Read JSON from stdin
data=$(cat /dev/stdin)

official_signatures=$(echo $data | jq -r '.OfficialSignatures')
unofficial_signatures_rating=$(echo $data | jq -r '.UnofficialSignaturesRating')

/sbin/e-smith/config setprop clamd OfficialSignatures "$official_signatures" UnofficialSignaturesRating "$unofficial_signatures_rating"

if [ $? -gt 0 ]; then
    invalid_error
fi

/sbin/e-smith/signal-event -j nethserver-antivirus-save
if [ $? -gt 0 ]; then
    error "EventFailed" "See /var/log/messages"
else
    success
fi
