#!/bin/bash

FOUND=0
eicar_db=/var/clamav/eicar.ndb

# Ensure Eicar signature is present, at least:
echo "Creating empty clamav signatures DB in ${eicar_db}.."
echo "Eicar-Test-Signature:0:0:58354f2150254041505b345c505a58353428505e2937434329377d2445494341522d5354414e444152442d414e544956495255532d544553542d46494c452124482b482a" > $eicar_db
[ -e $eicar_db ] && chown clamav.clamav $eicar_db

# Check if a mirror is reachable then start freshclam 
for MIRROR in `sed -n '/^DatabaseMirror/ s/DatabaseMirror // p' /etc/freshclam.conf`; do
    if nc -z $MIRROR 80; then
	echo "Starting freshclam.."
	/usr/bin/nohup /usr/bin/freshclam --quiet >/dev/null 2>&1 &
	exit 0;
    else
	echo "Unreachable mirror ${MIRROR}"
    fi
done

echo "WARNING: no more mirrors to try. clamav DB was not updated!" 1>&2
exit 0
