#!/bin/bash
#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

db_dir=/var/lib/clamav
eicar_db=${db_dir}/eicar.ndb

# Early exit if eicar.ndb is already present
if [ ! -e $eicar_db ]; then
    # Ensure Eicar signature is present, at least:
    echo "Creating empty clamav signatures DB in ${eicar_db}.."
    echo "Eicar-Test-Signature:0:0:58354f2150254041505b345c505a58353428505e2937434329377d2445494341522d5354414e444152442d414e544956495255532d544553542d46494c452124482b482a" > $eicar_db
    [ -e $eicar_db ] && chown --reference=${db_dir} $eicar_db
fi

# Manage official signatures
officialsig=$(/sbin/e-smith/config getprop clamd OfficialSignatures)
if [ "$officialsig" == "disabled" ]; then
    rm -f /var/lib/clamav/{bytecode.???,daily.???,main.???}
fi

# Remove old unused clamav-unofficial-sigs config file
rm -f /etc/clamav-unofficial-sigs/clamav-unofficial-sigs.conf

# Restart all clamd instances
systemctl try-restart clamd@*

# Temporary fix for https://bugzilla.redhat.com/show_bug.cgi?id=1794506
sed -i  's/MAILTO=root/MAILTO=/' /etc/cron.d/clamav-unofficial-sigs
