#!/usr/bin/perl

#
# Copyright (C) 2014 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use POSIX qw(setsid);

close(STDOUT);
close(STDERR);

my $pid = fork();

if($pid) {
    exit(0);
} else {
    open STDIN,  '<', '/dev/null' || die;
    open STOUT,  '>', '/dev/null' || die;
    open STDERR,  '>', '/dev/null' || die;
    setsid();
    sleep(rand(60*30));
    exec('/etc/cron.daily/freshclam');
}


